version: '3'
services:
  app:
    container_name: stock-server
    image: stock-server:v1
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/stock/logs:/stock-service/logs
      - ~/docker/stock/upload:/stock-service/upload
      - ~/docker/stock/bad:/stock-service/bad
  redis:
    container_name: redis
    image: redis:v1
    build: ./docker/redis
    hostname: redis
    ports:
      - "6379:6379"